cmd/continuity/continuityfs: SA1019: fuse.ENOENT is deprecated
    Error: continuityfs/fuse.go:200:15: SA1019: fuse.ENOENT is deprecated: Return a syscall.Errno directly. See ToErrno for exact rules. (staticcheck)
            return nil, fuse.ENOENT
                        ^

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>